### ISSUE TITLE
[UC]Manage course and section

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#1]

**Comment by lance-huang-nucloudglobal** [comment]
@nucloud-agutierrez 
you shall continue with SQA's TC when you are available

@apetitnucloud 
Below test is based on 
https://trello-attachments.s3.amazonaws.com/556bdadbae6f6ced74c60837/55929dae1d753a0f7006ea15/0cd66d823140077db90a9ac62bc472b1/%5BConde_Nast_LMS%5D%5BS.09%5DTC.xlsx

**TEST RESULT**
PA = Pass
**NG = Not pass**
ER = Expected result
AR = Actual result

Login LMS as top-account admin
Part 1------
1. Setup correct sub-account in LMS
ADBC, ADD
2. Setup incorrect sub-account in LMS
All other sub-account which does not have exact name as CRM course department

Part 2------
1. Confirm with DEV the integration cron job frequency
every sharp hour. eg. 14:00, 15:00

Part 3------
1. Check if courses are under correct sub-account
PA
2. Check if the course name is correct
NG
ER = The Universe of Perfume/香水品鉴
AR = The Universe of Perfume
3. Check if the reference code is correct
PA
4. Check if the section is under correct course
PA
5. Check if the section name is correct
PA
6. Check if the section start/end date is correct
PA

Part 4------
1. Change some integrated course name in CRM
At 13:55, http://crmsqa.nucloudglobal.net/web#id=5&view_type=form&model=cdn.courses&menu_id=222&action=215
2. Change some integrated intake name CRM
At 13:57, http://crmsqa.nucloudglobal.net/web#id=9&view_type=form&model=cdn.intakes&menu_id=223&action=216
3. Change some integrated intake start/end date
At 13:58, http://crmsqa.nucloudglobal.net/web#id=9&view_type=form&model=cdn.intakes&menu_id=223&action=216
WAS =  start - 11/02/2015 end - 02/05/2016
IS = start - 11/03/2015 end 02/06/2016
4. Wait the cron to run
Check again at 14:10
5. Check if the course name is correct
NG
ER = course name: Fashion Marketing & Branding -> Fashion Marketing & Branding(name changed) (note the name shall contains ZH)
AR = a new course named as Fashion Marketing & Branding(name changed) is created
6. Check if the reference code is correct
NG, since Part4-#5 is NG
7. Check if the section name is correct
NG, since Part4-#5 is NG
8. Check if the section start/end date is correct
NG, since Part4-#5 is NG
9. Check if there is duplicated course/intake integrated
NG, since Part4-#5 is NG

Part 5------
Check if courses and sections still can be manually created - Default LMS function
PA

**Comment by lance-huang-nucloudglobal** [comment]
Login LMS as top-account admin

------
Part 1
1. Setup correct sub-account in LMS
ADBC, ADD

2. Setup incorrect sub-account in LMS
All other sub-account which does not have exact name as CRM course department

------
Part 2
1. Confirm with DEV the integration cron job frequency
every sharp hour. eg. 14:00, 15:00

------
Part 3: Check if all course under correct sub-account
1. Check if courses are under correct sub-account
PA

2. Check if the course name is correct
PA
FS adjusted: https://trello-attachments.s3.amazonaws.com/556bdadbae6f6ced74c60837/55929dae1d753a0f7006ea15/f92e3c40d8ef1efe54c39218adbca82b/%5BConde_Nast_LMS%5D%5BS.09%5DFunctional_specification_20150916_V1.3.pdf

3. Check if the reference code is correct 
PA

4. Check if the section is under correct course 
PA

5. Check if the section name is correct 
PA

6. Check if the section start/end date is correct 
PA

------
Part 4: Check if changes on course and intake will be integrated
1. Change some integrated course name in CRM
At 11:08, http://crmsqa.nucloudglobal.net/web#id=5&view_type=form&model=cdn.courses&menu_id=222&action=215

2. Change some integrated intake name CRM
At 11:09, 
http://crmsqa.nucloudglobal.net/web#id=9&view_type=form&model=cdn.intakes&menu_id=223&action=216
http://crmsqa.nucloudglobal.net/web#id=6&view_type=form&model=cdn.intakes&menu_id=223&action=216

3. Change some integrated intake start/end date
At 11:12, http://crmsqa.nucloudglobal.net/web#id=6&view_type=form&model=cdn.intakes&menu_id=223&action=216
WAS = start - 10/12/2015 end - 01/24/2016
IS = start - 10/13/2015 end 01/25/2016

4. Wait the cron to run
Check again at 11:38 (Dev informed the cron was runing every 5 mins, will change it to once every hour)

5. Check if the course name is correct
PA

6. Check if the reference code is correct
PA

7. Check if the section name is correct
PA

8. Check if the section start/end date is correct
PA

9. Check if there is duplicated course/intake integrated
PA

------
Part 5: Check if courses and sections still can be manually created
1. Check if courses and sections still can be manually created - Default LMS function
PA

**Comment by nucloud-agutierrez** [comment]
Login LMS as top-account admin

------
Part 1
1.Setup correct sub-account in LMS
ADBC 

2.Setup incorrect sub-account in LMS
All other sub-account which does not have exact name as CRM course department

------
Part 2
1.Confirm with DEV the integration cron job frequency
every sharp hour. eg. 14:00, 15:00

------
Part 3: Check if all course under correct sub-account
1.Check if courses are under correct sub-account
PA

2.Check if the course name is correct
PA

3.Check if the reference code is correct 
PA

4.Check if the section is under correct course 
PA

5.Check if the section name is correct 
PA

6.Check if the section start/end date is correct 
PA

------
Part 4: Check if changes on course and intake will be integrated
1.Change some integrated course name in CRM

2.Change some integrated intake name CRM

3.Change some integrated intake start/end date

4.Wait the cron to run

5.Check if the course name is correct

6.Check if the reference code is correct

7.Check if the section name is correct

8.Check if the section start/end date is correct

9.Check if there is duplicated course/intake integrated

------
Part 5: Check if courses and sections still can be manually created
1.Check if courses and sections still can be manually created - Default LMS function

**Comment by lance-huang-nucloudglobal** [comment]
@nucloud-agutierrez 
I am not sure the test result is correct.
I change the course name in UAT CRM
![image](https://cloud.githubusercontent.com/assets/8621588/10932184/9af53ad0-8309-11e5-8684-4657ae375ab0.png)

at 15:35, I check the UAT LMS, see
![image](https://cloud.githubusercontent.com/assets/8621588/10932191/ab431b6e-8309-11e5-9282-03589ac528e7.png)

Could you pls recheck all NGs asap.

P.S. in the latest test result, what I C by opening the link given in Part 2:
1.I do not see the course name is changed, it is still "Fashion Media & Digital Communication"
2.I do see the intake name is changed, but it is changed in a course which never synced into LMS becasue it is a course under ADD, and there's no ADD sub-accont in LMS
3.the intake start/end date change link is from TEST env

**Comment by nucloud-agutierrez** [comment]
Login LMS as top-account admin

------
Part 1
1.Setup correct sub-account in LMS
ADBC 

2.Setup incorrect sub-account in LMS
All other sub-account which does not have exact name as CRM course department

------
Part 2
1.Confirm with DEV the integration cron job frequency
every sharp hour. eg. 14:00, 15:00

------
Part 3: Check if all course under correct sub-account
1.Check if courses are under correct sub-account
PA

2.Check if the course name is correct
PA

3.Check if the reference code is correct 
PA

4.Check if the section is under correct course 
PA

5.Check if the section name is correct 
PA

6.Check if the section start/end date is correct 
PA

------
Part 4: Check if changes on course and intake will be integrated
1.Change some integrated course name in CRM
http://crmuat.condenastcenter.com.cn/web#id=4&view_type=form&model=cdn.courses&menu_id=222&action=215

2.Change some integrated intake name CRM
http://crmuat.condenastcenter.com.cn/web#id=8&view_type=form&model=cdn.intakes&menu_id=223&action=216

3.Change some integrated intake start/end date
From : Intake Start Date 10/12/2015
Intake End Date 12/18/2015

To : Intake Start Date 11/03/2015
Intake End Date 11/16/2015

4.Wait the cron to run
Not Confirmed

5.Check if the course name is correct
PA

6.Check if the reference code is correct
PA

7.Check if the section name is correct
PA

8.Check if the section start/end date is correct
PA

9.Check if there is duplicated course/intake integrated
PA

------
Part 5: Check if courses and sections still can be manually created
1.Check if courses and sections still can be manually created - Default LMS function
PA

**Comment by nucloud-agutierrez** [comment]
Login LMS as top-account admin

------
Part 1
1.Setup correct sub-account in LMS
ADBC 

2.Setup incorrect sub-account in LMS
All other sub-account which does not have exact name as CRM course department

------
Part 2
1.Confirm with DEV the integration cron job frequency
PROD: every 24 hours(00:00) per FS

------
Part 3: Check if all course under correct sub-account
1.Check if courses are under correct sub-account
PA

2.Check if the course name is correct
PA

3.Check if the reference code is correct 
PA

4.Check if the section is under correct course 
PA

5.Check if the section name is correct 
PA

6.Check if the section start/end date is correct 
PA

------
Part 4: Check if changes on course and intake will be integrated
1.Change some integrated course name in CRM

2.Change some integrated intake name CRM

3.Change some integrated intake start/end date

4.Wait the cron to run
PROD: every 24 hours(00:00) per FS

5.Check if the course name is correct


6.Check if the reference code is correct


7.Check if the section name is correct


8.Check if the section start/end date is correct


9.Check if there is duplicated course/intake integrated


------
Part 5: Check if courses and sections still can be manually created
1.Check if courses and sections still can be manually created - Default LMS function
