### ISSUE TITLE
[UC]View look & feel for desktop version(all pages)

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#28]
FS: https://trello.com/c/gaKIo30S/13-responsive-design-guideline

John can complete this UC without UX designer

**Comment by jbaltazar** [comment]
<b>Note: </b>
    Base url is depend on Server Environment Url. So far we have specific base url for Test,Dev,SQA and UAT

    Example:
        For Test Environment this is the base url
            http://lmstest.nucloudglobal.net:3000

        If you want to check all pages below. You can do it by Base URL with Specific URI
            Example:
                http://lmstest.nucloudglobal.net:3000/calendar


<b>@-Overriding CSS Files is for</b>
<ul>
    <li>Link(Active,Visited,Hover)</li>
    <li>Form object(Button, Radio, Checkbox, Textbox, Textarea etc)</li>
    <li>h1,h2,h3,h4,h5,h6</li>
    <li>Table</li>
    <li>TinyMCE</li>
    <li>Login Page</li>
</ul>

<b>@-List of URI</b>
<b>#-STANDARD FEATURE FOR ALL USER</b>
<ul>
<li>
    <b>Login</b><br>
    /login/canvas
</li>
<li>
    <b>Dashboard</b><br>
    /
</li>
<li>
    <b>ePortfolio</b><br>
    /dashboard/eportfolios
</li>
<li>
    <b>Calendar</b><br>
    /calendar
</li>
<li>
    <b>Profile</b><br>
    /about/{USER-ID}
</li>
<li>
    <b>Notification</b><br>
    /profile/communication
</li>
<li>
    <b>Settings</b><br>
    /settings
</li>
</ul>

<b>#-SITE ADMIN (SUPER ADMIN)</b>
<ul>
<li>
    <b>Users</b><br>
    /accounts/{SUPER-ADMIN-ID}/users
</li>
<li>
    <b>Permission</b><br>
    /accounts/{SUPER-ADMIN-ID}/permissions
</li>
<li>
    <b>Sub Accounts</b><br>
    /accounts/{SUPER-ADMIN-ID}/sub_accounts
</li>
<li>
    <b>Authentication</b><br>
    /accounts/{SUPER-ADMIN-ID}/authentication_providers
</li>
<li>
    <b>Plugins</b><br>
    /plugins
</li>
<li>
    <b>Developer Key</b><br>
    /developer_keys
</li>
<li>
    <b>Settings Page and it's tab for (Settings,Quotas,NotificationAdmin,Announcement,Reports,Apps,Feature Options)</b><br>
    /accounts/{SUPER-ADMIN-ID}/settings
</li>
</ul>

<b>#-CONDENAST ACCOUNT (TOP ACCOUNT)</b>
<ul>
<li>
    <b>Courses</b><br>
    /accounts/{TOP-ACCOUNT-ID}
</li>
<li>
    <b>Users</b><br>
    /accounts/{TOP-ACCOUNT-ID}/users
</li>
<li>
    <b>Statistics</b><br>
    /accounts/{TOP-ACCOUNT-ID}/statistics
</li>
<li>
    <b>Permissions</b><br>
    /accounts/{TOP-ACCOUNT-ID}/permissions
</li>
<li>
    <b>Outcomes</b><br>
    /accounts/{TOP-ACCOUNT-ID}/outcomes
</li>
<li>
    <b>Rubrics</b><br>
    /accounts/{TOP-ACCOUNT-ID}/rubrics
</li>
<li>
    <b>Grading</b><br>
    /accounts/{TOP-ACCOUNT-ID}/grading_standards
</li>
<li>
    <b>Question Banks</b><br>
    /accounts/{TOP-ACCOUNT-ID}/question_banks
</li>
<li>
    <b>Sub Accounts</b><br>
    /accounts/{TOP-ACCOUNT-ID}/sub_accounts
</li>
<li>
    <b>Terms</b><br>
    /accounts/{TOP-ACCOUNT-ID}/terms
<li>
    <b>Authentication</b><br>
    /accounts/{TOP-ACCOUNT-ID}/authentication_providers
</li>
<li>
    <b>Admin Tools</b><br>
    /accounts/{TOP-ACCOUNT-ID}/admin_tools
</li>
<li>
    <b>Settings Page and it's tab for (Settings,Quotas,Notification,Admins,Announcements,Reports,Apps,Feature Options)</b><br>
/accounts/{TOP-ACCOUNT-ID}/settings
</li>
</ul>

<b>#-FOR OTHER ROLE ACCOUNTS (STUDENT, TEACHER, ACCOUNT ROLES, COURSE ROLES)</b>
- All changes for custom desktop view is already applied for this roles where the changes is dependent from Super Admin and Top Account

See the Pull Request Information here:

**Comment by jbaltazar** [comment]
For this UC, I can see that all files is already merged in [Dev Repository](https://github.com/nucloudglobal/lms/pull/3/files) but not being pull in [lmssqa.nucloudglobal.net](http://lmssqa.nucloudglobal.net). Kindly pull this so that SQA can start testing it.

See screenshot:
![public_directory](https://cloud.githubusercontent.com/assets/7844693/10782649/11a480b4-7d8d-11e5-9575-5e5c1a1b9b52.png)

**Comment by jbaltazar** [comment]
This one is already applied in SQA Server even this is from Sprint 5. This is ready for testing.

**Comment by lance-huang-nucloudglobal** [comment]
do not know why it is not label as TEST ready, maybe it is not part of current Sprints?

@nucloud-agutierrez , the testing of this requires you follow the GUI guideline doc.

**Comment by nucloud-agutierrez** [comment]
QA20151030: QA tested. Fixed.

**Header** - Passed
**Footer** - Passed
**Main Content Section (left side)** - Passed
**Side Content Section (right side)** - Passed
**Typography (All text)** - Passed
**Images** - Passed
**Tables** - Passed

*Form elements*
**Text box** - Passed
**Combo box / Dropdown menu -List box** - Passed
**Check box** - Passed
**Radio button** - Passed
**Text area** - Passed
**Button** - Passed
**Progress bar** - Passed
**Text labels** - Passed

**Comment by lance-huang-nucloudglobal** [comment]
@nucloud-agutierrez 
I may not sure about if this the "Fixed"
I can already see the difference from FS:
![image](https://cloud.githubusercontent.com/assets/8621588/10838173/542fab4a-7efd-11e5-9c13-fda8bc23a141.png)

but I do like the current login screen which is clean, let me ask client to see if I can persuade them to give up to have the footer in login screen.

**Comment by lance-huang-nucloudglobal** [comment]
@nucloud-agutierrez 
The testing critieria shall from FS, GUI guiline doc but not the partial and initial CSS made by James.
The one confirmed by client is the FS only.
https://trello-attachments.s3.amazonaws.com/556bdadbae6f6ced74c60837/55b0a953f539e94829c27f3e/a87f78cbbd99f7216ea269ffa5cbac15/%5BConde_Nast_LMS%5DResponsive_design_guideline_20150805_V1.0.pdf

I can see more place has issues, for example, color of RED. James did not complete all CSS things in that https://trello.com/c/TtGuVGgk/20-css-override-initial-and-partial, and some of the elemenets' styling are different from the FS also made by James and confirmed by client.

CC @jbaltazar @apetitnucloud

**Comment by apetitnucloud** [comment]
@lance-huang-nucloudglobal this is really hard to test for @nucloud-agutierrez if you come to the red color differences and if you don't provide her PSD or the code color of each element ....

**Comment by lance-huang-nucloudglobal** [comment]
no need for PSD for red color testing, I do not even think Joy need to "test" it if the color looks close :)
yes, they are very different.(If ECW's red is red, then current LMS is too light)

The red shall be same as the one used in ECW, @John, just use the color code used in ECW
@jbaltazar @nucloud-agutierrez

**Comment by nucloud-agutierrez** [comment]
Login Page - it should show the footer as what is in the GUI Responsive design guideline.

User Dashboard 
- Start a New Course button should be white and not red
- Welcome to Canvas! should be bold
- Configure Communication Preferences link should br bold
- Configure Communication Preferences text inside the button should be black
- Coming Up text should be bold
- View Calendar link should be bold
- It should also show the footer
- Font style should be the same as what is in ECW

Courses Page
- Courses In This Account text should be bold
- Add a New Course button should be white
- Add New User buttob should be white
- Course Filtering text should be bold
- It should also show the footer
- Font style should be the same as what is in ECW

Calendar
- There should be a scheduler button
- Calendar collapsible label should be black
- Undated items collapsible label should be black
- Font style should be the same as what is in ECW

Settings
- [User].com's Settings text should be bold
- Web Services text should be bold
- Registered Services text should be bold
- Approved Integrations text should be bold
- Feature Options text should be bold
- Edit Settings button should be white
- Download Submissions button should be white
- New Access Token button should be white
- Font style should be the same as what is in ECW

**Comment by jbaltazar** [comment]
<h3>Pending</h3>

**User Dashboard**
- It should also show the footer

**Course Page**
- It should also show the footer

**Calendar**
- None

**Settings**
- None

<hr>
<h3>Notes:</h3>
1] LMS is now using the same Font with ECW which is the 
- ProximaNov*
- DINPro-*
- FZLanTingHei-EL*

2] We can test this UC without the footer section and label it as "<i><b>Test Ready</b></i>" where right now, We still don't have the final decision for the footer content.

[See code for reference]()

**Comment by lance-huang-nucloudglobal** [comment]
@jbaltazar 
Client confirmed the footer needs to exist as confirmed in GUI guideline V1.0, **however,** footer can be hardwired (static) as currently shown in FCW/ECW. 

Be noted that 
1.Some txt in footer may change, for example: ADMISSION OFFICE: 21/F WHEELOCK SQUARE, NO. 1717 WEST NANJING ROAD, JINGAN DISTRICT, SHANGHAI, 200040, PRC

2.two languages

CC @apetitnucloud @nucloud-agutierrez

**Comment by lance-huang-nucloudglobal** [comment]
@jbaltazar 
Be note of this asl well:
1.I can see the placeholder of login form is different in TEST and UAT
2.the bg image shall be same the one being used in TEST/PROD ECW ( @apetitnucloud  , we forgot to update the UAT ECW bg image.)

CC @nucloud-agutierrez

**Comment by jbaltazar** [comment]
@apetitnucloud 

I already finished the Hardcoded footer. I'm going to create a new pull request so that it can be test now in SQA and UAT.

Thank you

**Comment by jbaltazar** [comment]
Hardcoded Footer is now on pull request.

[View Pull Request](https://github.com/nucloudglobal/lms/pull/6)

**Comment by jbaltazar** [comment]
<b>Login Footer</b>
![login_footer](https://cloud.githubusercontent.com/assets/7844693/10929339/42bcdba0-82ed-11e5-9595-0d7bc70a3941.png)

<b>Dashboard Footer</b>
![dashboard_footer](https://cloud.githubusercontent.com/assets/7844693/10929350/5dc342ae-82ed-11e5-8704-699281005eaa.png)

**Comment by jbaltazar** [comment]
@lance-huang-nucloudglobal 

For this question:
1.I can see the placeholder of login form is different in TEST and UAT
- <i>Login form is already changed see screenshot above for the login page.</i>

2.the bg image shall be same the one being used in TEST/PROD ECW ( @apetitnucloud , we forgot to update the UAT ECW bg image.)
- <i>This one is also updated upon deploying the latest changes.</i>

Thank you

**Comment by jbaltazar** [comment]
@lance-huang-nucloudglobal 

For this question:
1.Some txt in footer may change, for example: ADMISSION OFFICE: 21/F WHEELOCK SQUARE, NO. 1717 WEST NANJING ROAD, JINGAN DISTRICT, SHANGHAI, 200040, PRC
- Right now, due of we are using the Hardcoded method. if the footer content change in the FCW/ECW then we need to update the footer in LMS manually.

2.two languages
- This one will be transfer in another UC as per skype conversation.

Thank you

**Comment by lance-huang-nucloudglobal** [comment]
@jbaltazar 
This one will go to different UC ticket if it is not fixed when that UC card is tested, I can see the login screen is in ZH version, but some item is in EN:
![image](https://cloud.githubusercontent.com/assets/8621588/10958726/2b1e59f0-83ac-11e5-9f00-b55a07e101d5.png)

for the bg img, pls use this one:
https://my.condenastcenter.com.cn/zh-hans/users/login

**Comment by ajmgutierrezsimplenight** [comment]
@lance-huang-nucloudglobal 

This is one of what @apetitnucloud say in our group chat conversation. Some of them is hardcoded and some of the is .yml. will check what we can do to generally fix this one.

**Comment by jbaltazar** [comment]
This one is the same thing that @apetitnucloud is talking about in our group skype conversation. Some of the is hardcoded and some of them is via .yml. will check this one for the general fix.

**Comment by jbaltazar** [comment]
@apetitnucloud 

I created another pull request just to fix the background image.

![background_image](https://cloud.githubusercontent.com/assets/7844693/10961229/8710e172-83c7-11e5-9da1-b604c2b781b0.png)

[See Pull Request Info](https://github.com/nucloudglobal/lms/pull/7)

**Comment by lance-huang-nucloudglobal** [comment]
See the separate UC about language in https://github.com/nucloudglobal/lms-ext/issues/30

**Comment by nucloud-agutierrez** [comment]
Login Page 
- it should show the footer as what is in the GUI Responsive design guideline - *Passed*

User Dashboard

- Start a New Course button should be white and not red - *Passed*
- Welcome to Canvas! should be bold - *Passed*
- Configure Communication Preferences link should br bold - *Passed*
- Configure Communication Preferences text inside the button should be black - *Passed*
- Coming Up text should be bold - *Passed*
- View Calendar link should be bold - *Passed*
- It should also show the footer - *Passed*
- Font style should be the same as what is in ECW - *Passed*

Courses Page

- Courses In This Account text should be bold - *Passed*
- Add a New Course button should be white - *Passed*
- Add New User buttob should be white - *Passed*
- Course Filtering text should be bold - *Passed*
- It should also show the footer - *Passed*
- Font style should be the same as what is in ECW - *Passed*

Calendar

- There should be a scheduler button
Calendar collapsible label should be black
Undated items collapsible label should be black
Font style should be the same as what is in ECW
Settings

[User].com's Settings text should be bold
Web Services text should be bold
Registered Services text should be bold
Approved Integrations text should be bold
Feature Options text should be bold
Edit Settings button should be white
Download Submissions button should be white
New Access Token button should be white
Font style should be the same as what is in ECW

**Comment by jbaltazar** [comment]
@apetitnucloud kindly update the ENV so that we can close this UC too.

**Comment by nucloud-agutierrez** [comment]
QA20160128: QA tested. Fixed in PROD Environment.

Login Page 
- it should show the footer as what is in the GUI Responsive design guideline - *Passed*

User Dashboard

- Start a New Course button should be white and not red - *Passed*
- Welcome to Canvas! should be bold - *Passed*
- Configure Communication Preferences link should br bold - *Passed*
- Configure Communication Preferences text inside the button should be black - *Passed*
- Coming Up text should be bold - *Passed*
- View Calendar link should be bold - *Passed*
- It should also show the footer - *Passed*
- Font style should be the same as what is in ECW - *Passed*

Courses Page

- Courses In This Account text should be bold - *Passed*
- Add a New Course button should be white - *Passed*
- Add New User buttob should be white - *Passed*
- Course Filtering text should be bold - *Passed*
- It should also show the footer - *Passed*
- Font style should be the same as what is in ECW - *Passed*

Calendar

- There should be a scheduler button - *Passed*
- Calendar collapsible label should be black - *Passed*
- Undated items collapsible label should be black - *Passed*
- Font style should be the same as what is in ECW - *Passed*

Settings

- [User].com's Settings text should be bold - *Passed*
- Web Services text should be bold - *Passed*
- Registered Services text should be bold - *Passed*
- Approved Integrations text should be bold - *Passed*
- Feature Options text should be bold - *Passed*
- Edit Settings button should be white - *Passed*
- Download Submissions button should be white - *Passed*
- New Access Token button should be white - *Passed*
- Font style should be the same as what is in ECW - *Passed*

Background Image

- Background image should be the single girl - *Passed*
