### ISSUE TITLE
Increase UAT and PROD HDD

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#43]
@apetitnucloud 

Jessica has bought the 1000GB HDD for both UAT and PROD

Pls first practice the HDD increasing action on UAT env.
**Pls make sure the data will not be lost**, find below as the reference doc from Aliyun of how to
 
https://help.aliyun.com/document_detail/ecs/operation-guide/disk-operation/resize.html?spm=5176.2020520101.0.0.vPpwHh

I have made the UAT snapshot:
![image](https://cloud.githubusercontent.com/assets/8621588/12315512/a231dada-bab6-11e5-9ff2-44769c645425.png)

Some important data numbers in UAT before the snapshot:
User = 20
Intake =13
Client = 47
Course application = 48

----------
Information:
For both UAT and PROD
ECW/CRM/LMS DB is on 20GB - not going to be an issue for 1-2 years

ECW uploaded file is on AWS S3
CRM uploaded files is on it's DB - 20GB disk
LMS uploaded file is on 1000GB disk

 all system logs are on 1000GB

----------

**Comment by lance-huang-nucloudglobal** [comment]
Step 2 in Aliyun manual: Server restart from Aliyun platform is done at 2016-Jan-18 15:10

CC @apetitnucloud

**Comment by lance-huang-nucloudglobal** [comment]
Lance add UAT sqa verified label by receiving notification from @apetitnucloud that UAT HDD has been increased into 1000GB.

@apetitnucloud 
We need to prepare to do same thing on PROD, which is:
1. How long it will take
2. Start from when
a) I snapshot both disks and restart the server (Conde Nast advise to make it happen in early morning, such 8:00, not in the night)
b) you config the server
and we need to get **approval** for the time above before we do it
 
**Pls make sure the data will not be lost**

**Comment by apetitdev** [comment]
@lance-huang-nucloudglobal should take about 1 hour.
The Start from when to when should be define by client rather than me because we will shut down everything so main impact on their business.
"Pls make sure the data will not be lost"
We can't have lost since database isn't on this drive.

**Comment by lance-huang-nucloudglobal** [comment]
@apetitnucloud 
Conde nast has approved to do the HDD operation on PROD from 12:00 to 13:00 on Jan-20.
Step:
1. Lance snapshot the HDDs around 11:50
2. Lance restart the PROD server at 12:00
3. Aurelien proceed for the rest of the HDD operation
